"use client";

import { useEffect, useState } from "react";
import type { ClassroomCandidateResult } from "@/types/classroomResults";
import { achievement, buildTeacherSynthesis, metric, QUESTIONS, questionLevel, questions, supportedNotes, usable } from "@/services/teacherLessonSynthesis";

const panel = "rounded-2xl border border-slate-200 bg-white p-5";
function mode(mode: string) {
  return ({live_ai: "Live AI", mixed: "Mixed AI + Backup", backup_rubric: "Backup Rubric"} as Record<string,string>)[mode] ?? "Unavailable";
}
function display(value: number | null, suffix = "%") { return value === null ? "No data" : `${value}${suffix}`; }
function Notes({ title, values }: {title: string; values: unknown}) {
  const notes = supportedNotes(values);
  return <div><h4 className="font-bold">{title}</h4>{notes.length ? <ul className="mt-2 list-disc space-y-1 pl-5">{notes.map((v,i) => <li key={i}>{v}</li>)}</ul> : <p className="mt-2 text-slate-500">No supported content/language note available. Review the criteria and transcript.</p>}</div>;
}
export default function TeacherLessonSynthesis({ sessionId, results, expected }: {sessionId: string; results: ClassroomCandidateResult[]; expected: number}) {
  const synthesis = buildTeacherSynthesis(results);
  const [judgment, setJudgment] = useState("");
  const [saved, setSaved] = useState("");
  const storageKey = `english-ai-teacher-judgment-v4332:${sessionId}`;
  useEffect(() => {
    try { setJudgment(localStorage.getItem(storageKey) ?? ""); } catch { setSaved("Cannot read the saved teacher judgment on this browser."); }
  }, [storageKey]);
  function save() {
    try { localStorage.setItem(storageKey, judgment); setSaved("Saved on this teacher browser only; not synchronized to Supabase."); }
    catch { setSaved("Save failed. Copy your judgment before leaving this page."); }
  }
  return <section className="space-y-6 rounded-3xl border border-indigo-200 bg-slate-50 p-5 text-slate-900 shadow-xl sm:p-8">
    <header><p className="font-bold text-indigo-700">FIX 43.3.2 · {results.length}/{expected} Supabase results · No additional Gemini request</p><h2 className="mt-2 text-3xl font-black">Lesson Objective Achievement</h2><p className="mt-3 leading-7">Practice → Respond → Feedback → Reflect → Improve → Build Confidence</p><p className="mt-2 text-sm">These are provisional practice indicators, not final grades. Criteria: ≥70% meets practice target; 50–69% developing; &lt;50% needs focused practice. Q attainment uses the lowest of coverage, structure and evidence; all three must be present. Missing evidence is never zero. Overall score is supporting context only.</p></header>
    <div className="grid gap-4 lg:grid-cols-2">
      <article className={panel}><h3 className="font-black">1. Identify common job interview questions and answer structures.</h3><p className="mt-2">Interview responses provide indirect evidence of structure use; they do not establish explicit identification knowledge.</p><p className="mt-2 font-bold">Structure: {display(synthesis.indicators[1].value)} · {achievement(synthesis.indicators[1].value)}</p><p>Available for {synthesis.indicators[1].count}/{results.length * 3} answers. Teacher: ask learners to name the three questions and explain their answer sequences.</p></article>
      <article className={panel}><h3 className="font-black">2. Develop personalized interview answers and answer job interview questions in English.</h3><p className="mt-2">Review each student's Q1–Q3 criteria and transcript below. Scores alone do not establish personalization or English accuracy.</p>{synthesis.indicators.map(i => <p key={i.label} className="mt-2">{i.label}: <strong>{display(i.value)}</strong> · {i.count}/{results.length * 3} answers with data</p>)}</article>
      <article className={panel}><h3 className="font-black">3. Use AI tools to optimize content, correct grammar, and practice interview.</h3><p className="mt-2">Evaluation sources are shown per student and question. Receiving feedback does not prove that the learner used it to revise. Teacher verification needed: compare an original answer and a student revision; ask the learner to explain one grammar/content change.</p></article>
      <article className={panel}><h3 className="font-black">4. Engage in proactive learning and active teamwork.</h3><p className="mt-2">Teacher / peer observation required. Cloud completion does not prove active teamwork. Check role exchange, peer notes, initiative and one improvement agreed with the partner.</p></article>
    </div>
    <section className={panel}><h3 className="text-2xl font-black">Student Performance Overview</h3><p className="mt-2 text-sm">Original completion order; no student ranking. Open View Details for evidence, reflection and next steps.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr>{["Student", "Q1", "Q2", "Q3", "Evaluation mode"].map(h => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{results.map(r => <tr key={r.id} className="border-t"><th className="p-3">{r.candidate_name}</th>{questions(r).map((q,i) => <td key={i} className="p-3"><strong>{display(usable(q) ? metric(q?.score,10) : null,"/10")}</strong><p>{questionLevel(q)}</p></td>)}<td className="p-3">{mode(r.evaluation_mode)}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 lg:grid-cols-3">{synthesis.questionGroups.map((q,i) => <article key={q.title} className={panel}><h3 className="text-lg font-black">Q{i+1}: {q.title}</h3><p className="mt-2 text-sm">{q.structure}</p>{["Meets practice target", "Developing", "Needs focused practice", "Insufficient evidence"].map(level => <p key={level} className="mt-2">{level}: <strong>{q.levels.filter(v => v === level).length}/{results.length}</strong></p>)}<p className="mt-3 text-sm">Supporting score average: {display(q.scores.value,"/10")} ({q.scores.count} available)</p></article>)}</div>
    {results.map(r => <details key={r.id} className={panel}><summary className="cursor-pointer text-xl font-black">View Details · {r.candidate_name}</summary><p className="mt-3">{mode(r.evaluation_mode)} · Overall (context only): {display(metric(r.overall_score,10),"/10")}</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{questions(r).map((q,i) => <article key={i} className="rounded-xl bg-slate-50 p-4"><h4 className="font-black">Q{i+1}: {QUESTIONS[i].title}</h4><p className="mt-2 text-sm">{QUESTIONS[i].structure}</p><p className="mt-2 font-bold">{display(usable(q) ? metric(q?.score,10) : null,"/10")} · {questionLevel(q)}</p><p className="text-sm">Source: {mode(q?.source ?? "unavailable")}</p>{(["coverageScore", "structureScore", "evidenceQualityScore"] as const).map((key,j) => <p key={key} className="mt-2">{["Coverage", "Structure", "Evidence"][j]}: {display(usable(q) ? metric(q?.[key]) : null)}</p>)}<div className="mt-3 space-y-3"><Notes title="Strengths" values={usable(q) ? [q?.strength] : []}/><Notes title="Areas to Improve" values={usable(q) ? [q?.improvement] : []}/><h5 className="font-bold">Next Practice</h5><p>{QUESTIONS[i].practice}</p></div><details className="mt-3"><summary className="cursor-pointer font-bold">View transcript</summary><p className="mt-2 whitespace-pre-wrap break-words">{q?.transcript || "No transcript stored."}</p></details></article>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Notes title="Strengths" values={r.strengths}/><Notes title="Areas to Improve" values={r.improvements}/><Notes title="Next Practice · stored recommendations" values={r.recommended_next_practice}/></div><p className="mt-4 text-xs text-slate-600">Stored notes are prior evaluation statements, not independently verified observations. This result JSON does not retain criterion-level quotations or full grammar analysis. Unsupported behavioral/audio claims are omitted conservatively. Use transcripts and human observation to verify.</p></details>)}
    <div className="grid gap-4 lg:grid-cols-3"><article className={panel}><h3 className="font-black">Class Strengths</h3><p className="mt-2">{synthesis.strongest ? `${synthesis.strongest.label}: strongest available indicator at ${synthesis.strongest.value}% (${synthesis.strongest.count} answers). This relative strength does not mean every student meets the target.` : "Insufficient criterion data to identify a class strength."}</p></article><article className={panel}><h3 className="font-black">Priority Areas for Improvement</h3><p className="mt-2">{synthesis.priority ? `${synthesis.priority.label}: lowest available indicator at ${synthesis.priority.value}% (${synthesis.priority.count} answers). Check individual details before assigning practice.` : "Collect missing criteria and review transcripts before selecting a priority."}</p></article><article className={panel}><h3 className="font-black">Recommended Next Practice</h3><p className="mt-2">Each learner chooses one Q marked developing or needs focused practice, follows its Next Practice task, asks a partner for one content/structure comment, revises the answer, and explains the change to the teacher. If all meet target, transfer the answer to a new job/company.</p></article></div>
    <section className="rounded-2xl border-2 border-indigo-200 bg-indigo-50 p-5"><h3 className="text-xl font-black">Teacher Synthesis / Teacher Final Judgment</h3><p className="mt-2">The teacher makes the final judgment using response evidence, student revisions, peer notes and live observation. Eye contact, posture and directly observed behavior belong to peer observers and the teacher; this synthesis does not infer them.</p><label className="mt-4 block font-bold" htmlFor="teacher-judgment">Your final judgment and next lesson action</label><textarea id="teacher-judgment" value={judgment} onChange={e => {setJudgment(e.target.value);setSaved("");}} rows={5} className="mt-2 w-full rounded-xl border border-indigo-300 bg-white p-3" placeholder="Confirm achievement for each objective, cite evidence/observation, and choose one next practice action. This field is written by the teacher."/><button type="button" onClick={save} className="mt-3 rounded-xl bg-indigo-700 px-5 py-3 font-bold text-white">Save Teacher Judgment</button><p className="mt-2 text-sm" role="status">{saved || "Saved text stays on this browser only. Supabase schema is unchanged."}</p></section>
  </section>;
}
